#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define	MAXPACKET 4096
#define ARP_REPLY 0x02
#define ARP_REQUEST 0x01
#define BUF_SIZE 64
#define ETH2_HEADER_LEN 14
#define HW_TYPE 1
#define IPV4_BITLENGTH IPV4_LENGTH*8
#define IPV4_LENGTH 4
#define IPV6_LENGTH 16
#define MAC_BITLENGTH MAC_LENGTH*8
#define MAC_LENGTH 6
#define PROTO_ARP 0x0806

#define ETH_HDRLEN 14
#define IPV6_HDRLEN 40
#define ICMP_HDRLEN 8

#endif
